version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - ./:/app/log_in_s3_bucket_destroyer
      - app_poetry:/root/.cache/pypoetry
    working_dir: /app/log_in_s3_bucket_destroyer
    environment:
      PYTHONPATH: /app/log_in_s3_bucket_destroyer/log_in_s3_bucket_destroyer
      LOG_LEVEL: DEBUG
      ENVIRONMENT: development
      DUMMY_ENDPOINT_URL: http://minio:9000
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./docker_files/minio:/tmp/minio
    entrypoint: sh
    command: -c "
      minio server /data --address ':9000' --console-address ':9001';"

  minio_mc:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./docker_files/minio:/tmp/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: >
      /bin/sh -c "
      mc alias set s3 http://minio:9000 minio minio123;
      mc mb --region ap-northeast-1 s3/log-bucket-development;
      mc mb --region ap-northeast-1 s3/log-bucket-test;
      mc cp --recursive /tmp/minio/data/* s3/log-bucket-development;
      "

volumes:
  app_poetry:
    external: false
