version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - ./:/app/log_in_s3_bucket_destroyer
      - app_poetry:/root/.cache/pypoetry
    working_dir: /app/log_in_s3_bucket_destroyer
    environment:
      PYTHONPATH: /app/log_in_s3_bucket_destroyer/log_in_s3_bucket_destroyer
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true

volumes:
  app_poetry:
    external: false
