AWSTemplateFormatVersion: 2010-09-09

Description: This template create lambda function to destroy log files in S3 bucket on a schedule.

Parameters:
  Project:
    Description: Enter project name.
    Type: String
    Default: "sample"

  Environment:
    Description: Select environment.
    Type: String
    Default: common

  Function:
    Description: Enter function name.
    Type: String
    Default: log_in_s3_bucket_destroyer

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Basic Settings
        Parameters:
          - Project
          - Environment
          - Function

Resources:
  IAMUserDeployLambda:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub ${Function}_deployer
      Tags:
        - Key: Project
          Value: !Sub ${Project}
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Function
          Value: !Sub ${Function}

  IAMPolicyDeployLambda:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${Function}_deployer
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "lambda:UpdateFunctionCode"
            Resource: "*"
      Users:
        - !Ref IAMUserDeployLambda
      # Tags:
      #   - Key: Project
      #     Value: !Sub ${Project}
      #   - Key: Environment
      #     Value: !Sub ${Environment}
      #   - Key: Function
      #     Value: !Sub ${Function}
