AWSTemplateFormatVersion: 2010-09-09

Description: ''

Parameters:
  Project:
    Description: Enter project name.
    Type: String
    Default: ""

  Environment:
    Description: Enter environment.
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development

  Function:
    Description: Enter function name.
    Type: String
    Default: log_in_s3_bucket_destroyer

Resources:
  IAMRoleExecuteLambda:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Function}
      Description: This role is used by Lambda to execute the function.
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: Project
          Value: !Sub ${Project}
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Function
          Value: !Sub ${Function}

  IAMPolicyExecuteLambda:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${Function}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
              - "s3:DeleteObject"
            Resource: "*"
      Roles:
        - !Ref IAMRoleExecuteLambda

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${Function}
      # 一般設定
      Description: This function delete log files in S3 bucket.
      MemorySize: 128
      EphemeralStorage:
        Size: 512
      Timeout: 3
      SnapStart: # https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/snapstart.html?icmpid=docs_lambda_help
        ApplyOn: None
      # アクセス制限
      Role: !GetAtt IAMRoleExecuteLambda.Arn
      # 環境変数
      Environment:
        Variables:
          LOG_LEVEL: INFO
      PackageType: Zip
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              print(event)

              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
      # ランタイム設定
      Runtime: python3.12
      Handler: index.lambda_handler
      Architectures:
        - x86_64
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      LoggingConfig:
        LogGroup: !Ref LambdaLogGroup
      Tags:
        - Key: Project
          Value: !Sub ${Project}
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Function
          Value: !Sub ${Function}

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Function}
      RetentionInDays: 90
      Tags:
        - Key: Project
          Value: !Sub ${Project}
        - Key: Environment
          Value: !Sub ${Environment}
        - Key: Function
          Value: !Sub ${Function}
