name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Package
        run: |
            pip install poetry poetry-plugin-export
            poetry export -f requirements.txt --output requirements.txt --without dev
            pip install --target=lib -r requirements.txt

      - name: Deploy
        run: |
          zip -r deployment.zip lambda_handler.py log_in_s3_bucket_destroyer config/production.yaml lib

          aws lambda update-function-code \
            --function-name log_in_s3_bucket_destroyer \
            --zip-file fileb://deployment.zip
